### ISSUE TITLE
Remove deprecated canvas functions (x.cgm, x.raster, ...)

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat#1065]
You should probably remove the old unsupported output formats completely, or raise explicitly an exception saying that they are deprecated

I expect that you can probably find more of these error raising canvas functions  in http://uvcdat.llnl.gov/documentation/vcs/vcs-11.html#pgfId-912045

```
>>> help(x.cgm)

>>> x.cgm('cgm')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/share/unix_files/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_13/lib/python2.7/site-packages/vcs/Canvas.py", line 3785, in cgm
    return self.backend.cgm(file)
  File "/home/share/unix_files/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_13/lib/python2.7/site-packages/vcs/VTKPlots.py", line 1410, in cgm
    writer = vtk.vtkIOCGM.vtkCGMWriter()
AttributeError: 'module' object has no attribute 'vtkIOCGM'

>>> help(x.raster)

>>> x.raster('raster')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/share/unix_files/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_13/lib/python2.7/site-packages/vcs/Canvas.py", line 5287, in raster
    return apply(self.canvas.raster, (file,mode))
AttributeError: 'module' object has no attribute 'raster'

```

**Comment by chaosphere2112** [comment]
@doutriaux1 Hey, the CGM bit above looks like a bug, not a deprecation; is CGM something we're going to continue supporting? Should just be easy enough to switch the import to be correct. Can't speak to the raster call.
