### ISSUE TITLE
Exception while changing Dimensions

### ISSUE THREAD

**Issue by vvpalav** [CDAT/cdat#1277]
Getting multiple exceptions when dimensions is changed for variable. 

1) add variable from file.
2) change drop down to "Get Axis Value"

```
Traceback (most recent call last):
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/gui/uvcdat/axesWidgets.py", line 789, in getAxisValuesEvent
    le.setText("cdmsFile=cdms2.open('%s')" % self.parent.cdmsFile.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

Got this on calculator console:

```
Traceback (most recent call last):
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/gui/uvcdat/commandLineWidget.py", line 606, in run_command
    exec(compile(command, "<string>", "single"), __main__.__dict__)
  File "<string>", line 1, in <module>
NameError: name 'cdms2' is not defined
```

3) Now relaunch GUI change to "Get Axis Weight Values"

```
Traceback (most recent call last):
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/gui/uvcdat/commandLineWidget.py", line 606, in run_command
    exec(compile(command, "<string>", "single"), __main__.__dict__)
  File "<string>", line 1, in <module>
NameError: name 'cdms2' is not defined

Traceback (most recent call last):
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/core/modules/vistrails_module.py", line 327, in update
    self.compute()
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 705, in compute
    self.outvar.var = self.to_python()
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 674, in to_python
    res = eval(self.python_command)
  File "<string>", line 1, in <module>
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/genutil/averager.py", line 112, in getAxisWeightByName
    raise AveragerError, 'Could not get weights.'
AveragerError: ('C', 'o', 'u', 'l', 'd', ' ', 'n', 'o', 't', ' ', 'g', 'e', 't', ' ', 'w', 'e', 'i', 'g', 'h', 't', 's', '.')
ERROR:root:Uncaught exception: "('C', 'o', 'u', 'l', 'd', ' ', 'n', 'o', 't', ' ', 'g', 'e', 't', ' ', 'w', 'e', 'i', 'g', 'h', 't', 's', '.')"
None

Traceback (most recent call last):
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/gui/uvcdat/commandLineWidget.py", line 606, in run_command
    exec(compile(command, "<string>", "single"), __main__.__dict__)
  File "<string>", line 1, in <module>
NameError: name 'v_plev1_weight' is not defined
```

After this entire application becomes unresponsive.

**Comment by vvpalav** [comment]
More info in #1274
