### ISSUE TITLE
Exception in Scatter Plot: ZeroDivisionError

### ISSUE THREAD

**Issue by vvpalav** [CDAT/cdat#1280]
1) Load u, v and plot with Scatter plot.
2) Click on Next button (">") for prev variable and following exception comes up. Entire application become unresponsive.

```
Traceback (most recent call last):
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1725, in clicked
    cellWidget.updateContents(cellWidget.inputPorts,True)
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1450, in updateContents
    self.canvas.plot(cgm, *args, **kwargs)
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.py", line 2617, in plot
    a = self.__plot( arglist, keyargs )
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.py", line 3693, in __plot
    returned_kargs = self.backend.plot(*arglist, **keyargs)
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/VTKPlots.py", line 498, in plot
    returned.update(self.plot1D(data1,data2,tpl,gm))
  File /Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/VTKPlots.py", line 582, in plot1D
    self.canvas.plot(m,donotstoredisplay=True)
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.py", line 2617, in plot
    a = self.__plot(*arglist, **keyargs)
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.py", line 3693, in __plot
    returned_kargs = self.backend.plot(*arglist, **keyargs)
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/VTKPlots.py", line 486, in plot
    ren = self.fitToViewport(act,gm.viewport,wc=gm.worldcoordinate,geo=geo,priority=gm.priority)
  File "/Users/vinayakpalav/Documents/uvcdat_2_2/15-05-05/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/VTKPlots.py", line 1765, in fitToViewport
    xScale = vRatio*wRatio/dRatio
ZeroDivisionError: float division by zero
```

Before: Click highlighted button after plotting scatter plot with u and v

![screen shot 2015-05-05 at 8 58 20 pm](https://cloud.githubusercontent.com/assets/6840965/7485845/b62f3600-f369-11e4-8ba3-9c528dcbcd5f.png)

After button is clicked:

![screen shot 2015-05-05 at 8 52 47 pm](https://cloud.githubusercontent.com/assets/6840965/7485795/f2000fa2-f368-11e4-93c5-b37baf2d0420.png)

**Comment by dlonie** [comment]
Is there documentation for the GUI around? I found this, but it's very incomplete:

https://github.com/UV-CDAT/uvcdat/wiki/UVCDAT-GUI-Tutorials

I'm trying to figure out what that button does so I can write a vcs script to reproduce this without the GUI.

**Comment by dlonie** [comment]
@doutriaux1 @vvpalav

**Comment by dlonie** [comment]
I tried checking the "View Plot Source", but it doesn't change as a result of the button press.

**Comment by remram44** [comment]
> Is there documentation for the GUI around?

I agree, we desperately need this. The redesign effort could really use at least a list of requirements.

This button says "move to next dimensions", [here's the code](https://github.com/UV-CDAT/VisTrails/blob/22db59f593a411992204fe97275c620b828ade71/vistrails/packages/uvcdat_cdms/init.py#L1711-L1731). As for the "view plot source", anything that doesn't change provenance info won't be reflected there; in this case I think that is fine.

**Comment by dlonie** [comment]
@sankhesh will take a look, but we'll likely need help from @doutriaux1 to track this down :+1:
