### ISSUE TITLE
uvcdat installation: conflicting numba/uvcdat package specifications

### ISSUE THREAD

**Issue by puneet336** [CDAT/cdat#2199]
Dear All,
I am having issues while installing uvcdat , with coda 4.4.10 on centos 7.

Here is what i have sp far-
 
```
[spuneet@machine 3202018]$ conda install -c conda-forge uvcdat
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - uvcdat

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch


Now, as per instuctions at - https://anaconda.org/uvcdat/uvcdat
[spuneet@utility01 03202018]$ conda install -c uvcdat uvcdat
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - numba
  - uvcdat
Use "conda info <package>" to see the dependencies for each package.

[spuneet@machine 03202018]$
```

I have - 
numba                    0.36.2          np114py27he2868da_0

do i need to remove current version of numba?
If yes , then which verison of numba should i install ?
 please advice.

**Comment by puneet336** [comment]
UPDATE: i tried out various versions of anaconda  and 4.3.0 seems to have right version of libraries (conda is able to downgrade conflicts).

```
[spuneet@machine1 03202018]$ module load gnu/anaconda2/4.3.0
[spuneet@machine1 03202018]$ conda install -c uvcdat uvcdat
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0:

The following NEW packages will be INSTALLED:

    asciidata:          2.12-py27hbe9d963_0       uvcdat
    autopep8:           1.3.3-py_0                conda-forge
    basemap:            1.1.0-py27_4              conda-forge
    binaryio:           2.12-np111py27h044819a_0  uvcdat
    bzip2:              1.0.6-1                   conda-forge
    cdat_info:          2.12-py27_1               conda-forge
    cdms2:              2.12-np111py27_0          conda-forge
    cdp:                1.0.3-0                   uvcdat
    cdtime:             2.12-np111py27_2          conda-forge
    cdutil:             2.12-py27_0               conda-forge
    cibots:             0.2-py_0                  uvcdat
    clapack:            3.2.1-2                   uvcdat
    cloog:              0.18.0-0
    cssgrid:            2.12-np111py27h314ff11_0  uvcdat
    distarray:          2.12-py27_0               conda-forge
    dsgrid:             2.12-np111py27hc815344_0  uvcdat
    dv3d:               2.12-py27hac3d9b5_0       uvcdat
    eofs:               1.3.0-py27_0              conda-forge
    esmf:               7.0.0-8                   conda-forge
    esmpy:              7.0.0-py27_1              conda-forge
    ffmpeg:             2.7.0-UVCDAT              uvcdat
    flake8:             3.3.0-py27_0              conda-forge
    future:             0.16.0-py27_0             conda-forge
    g2clib:             1.4.0b-2                  uvcdat
    gcc:                4.8.5-7
    genutil:            2.12-np111py27_0          conda-forge
    geos:               3.6.2-1                   conda-forge
    gmp:                6.1.2-0                   conda-forge
    hdf5tools:          2.12-py27he5a1532_0       uvcdat
    isl:                0.12.2-0
    jasper:             1.900.1-2                 uvcdat
    krb5:               1.14.2-0                  conda-forge
    lapack:             3.4.2-UVCDAT              uvcdat
    libcdms:            2.4.1-UVCDAT              uvcdat
    libcf:              1.0.beta11-UVCDAT         uvcdat
    libdrs_f:           1.0.1-2                   uvcdat
    libnetcdf:          4.3.3.1-UVCDAT            uvcdat
    lmoments:           2.12-np111py27h58b1cd0_0  uvcdat
    lzo:                2.10-0                    conda-forge
    mccabe:             0.6.1-py27_0              conda-forge
    mpc:                1.0.3-4                   conda-forge
    mpfr:               3.1.5-0                   conda-forge
    mpi:                1.0-mpich                 conda-forge
    mpich:              3.2.1-0                   conda-forge
    natgrid:            2.12-np111py27h4f51b5e_0  uvcdat
    nb_conda:           2.2.1-py27_0              conda-forge
    nb_conda_kernels:   2.1.0-py27_0              conda-forge
    netcdf-fortran:     4.4.3-2                   conda-forge
    ort:                2.12-np111py27hfd1f69f_0  uvcdat
    ossuuid:            1.6.2-2                   uvcdat
    output_viewer:      1.2.3-py27h48dab56_0      uvcdat
    proj4:              5.0.0-0                   conda-forge
    pycodestyle:        2.3.1-py27_0              conda-forge
    pyproj:             1.9.5.1-py27_0            conda-forge
    pyshp:              1.2.12-py_0               conda-forge
    pyspharm:           1.0.9-py27_2              conda-forge
    regridpack:         2.12-np111py27hf311d9d_0  uvcdat
    shgrid:             2.12-np111py27hf037da4_0  uvcdat
    thermo:             2.12-py27h2ad96b2_0       uvcdat
    trends:             2.12-np111py27hdb0eb65_0  uvcdat
    udunits2:           2.2.25-1                  conda-forge
    uvcdat:             2.12-h4960ee3_0           uvcdat
    uvcmetrics:         2.2.1-np111py27_0         uvcdat
    vcs:                2.12-py27had75802_0       uvcdat
    vcsaddons:          2.12-py27h7706516_0       uvcdat
    vistrails:          2.12-h7b70e8b_0           uvcdat
    vtk-cdat:           7.1.0.2.12-py27hd6333ce_0 uvcdat
    windspharm:         1.5.1-py27_0              conda-forge
    wk:                 2.12-py27ha696ee6_0       uvcdat
    x264:               20131217-3                conda-forge
    xmgrace:            2.12-py27hb3ccff1_0       uvcdat
    zonalmeans:         2.12-np111py27h28606d6_0  uvcdat

The following packages will be UPDATED:

    anaconda:           4.3.0-np111py27_0                     --> custom-py27_0
    conda:              4.3.8-py27_0                          --> 4.3.34-py27_0     conda-forge
    h5py:               2.6.0-np111py27_2                     --> 2.7.1-py27_1      conda-forge
    hdf5:               1.8.17-1                              --> 1.8.18-1          conda-forge
    pytables:           3.3.0-np111py27_0                     --> 3.4.2-py27_5      conda-forge
    qtconsole:          4.2.1-py27_1                          --> 4.3.1-py27_0      conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    conda-env:          2.6.0-0                               --> 2.6.0-0           conda-forge


The following packages will be DOWNGRADED due to dependency conflicts:

    anaconda-navigator: 1.4.3-py27_0                          --> 1.2.3-py27_0
    matplotlib:         2.0.0-np111py27_0                     --> 1.5.1-np111py27_0
    pyqt:               5.6.0-py27_2                          --> 4.11.3-py27_1
    qt:                 5.6.2-3                               --> 4.8.6-3
    sip:                4.18-py27_0                           --> 4.16.5-py27_0

Proceed ([y]/n)? y
...................

Enabling nb_conda_kernels...
Enabled nb_conda_kernels

Enabling notebook extension nb_conda/main...
      - Validating: OK
Enabling tree extension nb_conda/tree...
      - Validating: OK
Enabling: nb_conda
- Writing config: /home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/etc/jupyter
    - Validating...
      nb_conda  OK
```

**Comment by doutriaux1** [comment]
@puneet336 conda install are standard and for stand alone packages, please see installation instructions at: https://github.com/CDAT/uvcdat/wiki/install

Lots of docs available at:

https://uv-cdat.llnl.gov

C.

**Comment by doutriaux1** [comment]
@puneet336 also we will be releasing or next version this upcoming week.

**Comment by puneet336** [comment]
I tried following the procedure at - 
, i am experiencing some issues with procedure - 
I had to create softlink for a dependent library & et the LD_LIBRARY_PATH & PYTHON path to get the vcs python uvcdat module working for me , here are the terminal logs from the installation -


```
[user@machine 03202018]$ conda create -n myuvcdat uvcdat -c conda-forge -c uvcdat
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat:

The following NEW packages will be INSTALLED:

    alabaster:                          0.7.10-py27_1             conda-forge
    asciidata:                          2.12-py27hbe9d963_0       uvcdat
    asn1crypto:                         0.24.0-py27_0             conda-forge
.....

mkl-2018.0.1-h 100% |#################################################################################################################| Time: 0:00
numpy-1.11.3-p 100% |#################################################################################################################| Time: 0:00
scipy-1.0.0-py 100% |#################################################################################################################| Time: 0:00
scikit-learn-0 100% |#################################################################################################################| Time: 0:00

+ /home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/bin/python -m nb_conda_kernels.install --enable --prefix=/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat
Enabling nb_conda_kernels...
Enabled nb_conda_kernels

+ /home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/bin/jupyter-nbextension enable nb_conda --py --sys-prefix
Enabling notebook extension nb_conda/main...
      - Validating: OK
Enabling tree extension nb_conda/tree...
      - Validating: OK
+ /home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/bin/jupyter-serverextension enable nb_conda --py --sys-prefix
Enabling: nb_conda
- Writing config: /home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/etc/jupyter
    - Validating...
      nb_conda  OK

#
# To activate this environment, use:
# > source activate myuvcdat
#
# To deactivate an active environment, use:
# > source deactivate
#


user@machine:~> source activate myuvcdat
(myuvcdat) user@machine:~> python
>>> import cdms2, cdat_info
>>> cdms2.__file__
'/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/python2.7/site-packages/cdms2/__init__.pyc'
>>> import vcs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/python2.7/site-packages/vcs/__init__.py", line 92, in <module>
    from utils import *  # noqa
  File "/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/python2.7/site-packages/vcs/utils.py", line 38, in <module>
    import vtk
  File "/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/python2.7/site-packages/vtk/__init__.py", line 87, in <module>
    from .vtkGeovisCore import *
  File "/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/python2.7/site-packages/vtk/vtkGeovisCore.py", line 9, in <module>
    from vtkGeovisCorePython import *
ImportError: No module named vtkGeovisCorePython
>>>

(myuvcdat) user@machine:~> python
Python 2.7.14 | packaged by conda-forge | (default, Dec 25 2017, 01:16:05)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import vcs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/python2.7/site-packages/vcs/__init__.py", line 92, in <module>
    from utils import *  # noqa
  File "/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/python2.7/site-packages/vcs/utils.py", line 38, in <module>
    import vtk
  File "/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/python2.7/site-packages/vtk/__init__.py", line 87, in <module>
    from .vtkGeovisCore import *
  File "/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/python2.7/site-packages/vtk/vtkGeovisCore.py", line 9, in <module>
    from vtkGeovisCorePython import *
ImportError: libproj.so.12: cannot open shared object file: No such file or directory
>>>

(myuvcdat) user@machine:~> ls /home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/libproj*
/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/libproj.a
/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/libproj.la
/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/libproj.so
/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/libproj.so.13
/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib/libproj.so.13.0.0


(myuvcdat) user@machine:/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0/envs/myuvcdat/lib> ln -s libproj.so.13 libproj.so.12
Python 2.7.14 | packaged by conda-forge | (default, Dec 25 2017, 01:16:05)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import vcs
>>>
>>>
>>>
>>>
```

please let me know what could be the behind this buggy installation.

**Comment by doutriaux1** [comment]
@puneet336 yes over the week-end proj4 (an external software) was update to v5 and it creates issue. please use:

````
conda create -n uvcdat -c conda-forge -c uvcdat uvcdat "proj4<5"
```

For you now please use (in your environment"

```
conda install -f -c conda-forge -c uvcdat "proj4<5"
```

It should solve your earlier issue.

proj4 version 5 is not backward compatible with uvcdat
