### ISSUE TITLE
tests are failing with Library not loade\ d: @rpath/libnetcdf.13.dylib -- install from mac yaml files

### ISSUE THREAD

**Issue by muryanto1** [CDAT/cdat#2215]
``macos_cdat-v80_py3 -- https://circleci.com/gh/CDAT/cdat/5320
macos_cdat-v80-nox_py3 -- https://circleci.com/gh/CDAT/cdat/5321
macos_cdat-v80-nox_py2 -- https://circleci.com/gh/CDAT/cdat/5317
macos_cdat-v80_py2 -- https://circleci.com/gh/CDAT/cdat/5316

many tests are failing with similar stack trace

============================================================
Executing nosetests -s /Users/distiller/project/workdir/cdms/tests/test_regrid2.py in /private/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/\
T/tmpcpi_0Z
E
======================================================================
ERROR: Failure: ImportError (dlopen(/Users/distiller/project/workdir/miniconda/envs/cdat-v80_py2/lib/python2.7/site-packages/cdtime.so, 2): L\
ibrary not loaded: @rpath/libnetcdf.13.dylib
  Referenced from: /Users/distiller/project/workdir/miniconda/envs/cdat-v80_py2/lib/python2.7/site-packages/cdtime.so
  Reason: image not found)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/distiller/project/workdir/miniconda/envs/cdat-v80_py2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromN\
ame
    addr.filename, addr.module)
  File "/Users/distiller/project/workdir/miniconda/envs/cdat-v80_py2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPat\
h
    return self.importFromDir(dir_path, fqname)
  File "/Users/distiller/project/workdir/miniconda/envs/cdat-v80_py2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/distiller/project/workdir/cdms/tests/test_variable_subselection.py", line 5, in <module>
    import cdms2
  File "/Users/distiller/project/workdir/miniconda/envs/cdat-v80_py2/lib/python2.7/site-packages/cdms2/__init__.py", line 20, in <module>
    from .cdmsobj import CdArray, CdChar, CdByte, CdDouble, CdFloat, CdFromObject, CdInt, CdLong, CdScalar, CdShort, CdString  # noqa
  File "/Users/distiller/project/workdir/miniconda/envs/cdat-v80_py2/lib/python2.7/site-packages/cdms2/cdmsobj.py", line 5, in <module>
    from . import cdmsNode
  File "/Users/distiller/project/workdir/miniconda/envs/cdat-v80_py2/lib/python2.7/site-packages/cdms2/cdmsNode.py", line 10, in <module>
    import cdtime
ImportError: dlopen(/Users/distiller/project/workdir/miniconda/envs/cdat-v80_py2/lib/python2.7/site-packages/cdtime.so, 2): Library not loade\
d: @rpath/libnetcdf.13.dylib
  Referenced from: /Users/distiller/project/workdir/miniconda/envs/cdat-v80_py2/lib/python2.7/site-packages/cdtime.so
  Reason: image not found
----------------------------------------------------------------------
Ran 1 test in 0.001s
FAILED (errors=1)

**Comment by muryanto1** [comment]
This issue is not applicable anymore
