### ISSUE TITLE
cdscan speed

### ISSUE THREAD

**Issue by pochedls** [CDAT/cdat#2231]
cdscan is a critical utility for using CMIP data. To create an xml file link to all CMIP datasets requires "scanning" order 10<sup>5</sup> files (possibly 10<sup>6</sup> files with CMIP6). 

The operation can be quite time consuming for some fields (this took ~2 minutes in earlier tests):

`time cdscan -x test.xml /p/css03/cmip5_css02/data/cmip5/output1/MIROC/MIROC5/historical/mon/ocean/Omon/r2i1p1/vo/1/*.nc`

> ...
> test.xml written
> real	4m16.473s
> user	0m12.279s
> sys	3m16.861s

and takes a surprising amount of memory: 

`top`

>  PID     USER      PR  NI  VIRT   RES   SHR S %CPU %MEM TIME+  COMMAND
> 13379 pochedle  20   0  464m  54m  15m R 100.5  0.0   0:17.31 cdscan

Is it possible to speed this up for a standard scan? Since the operation is done so frequently, it could be a really helpful improvement. Or maybe there are options I can use to drop unnecessary content from the xml file?

**Comment by doutriaux1** [comment]
@pochedls did you try the `-i` `-j` and `--time-linear` options?

**Comment by pochedls** [comment]
@doutriaux1 - I was worried about using some of these options, because I didn't know if linearity was always a good option. It seemed likely that some models may have done weird things that would breaj that assumption. 

The -j option doesn't speed things up. The -i and --time-linear options give me an error (not sure if it is my syntax or a bug). 

> time cdscan -x test.xml --time-linear /p/css03/cmip5_css02/data/cmip5/output1/MIROC/MIROC5/historical/mon/ocean/Omon/r2i1p1/vo/1/*.nc
Traceback (most recent call last):
  File "/export_backup/pochedley1/bin/anaconda2/envs/cdat81/bin/cdscan", line 1840, in <module>
    main(sys.argv)
  File "/export_backup/pochedley1/bin/anaconda2/envs/cdat81/bin/cdscan", line 837, in main
    ttzero = float(targlist[0])
ValueError: could not convert string to float: '/p/css03/cmip5_css02/data/cmip5/output1/MIROC/MIROC5/historical/mon/ocean/Omon/r2i1p1/vo/1/vo_Omon_MIROC5_historical_r2i1p1_185001-185012.nc'

**Comment by durack1** [comment]
@dnadeau4 @doutriaux1 this is a key enhancement request, can we get it put on the "PRIORITY" queue?

**Comment by dnadeau4** [comment]
I was working on this, but thought that it was no longer necessary to speed it up.

**Comment by durack1** [comment]
@dnadeau4 `cdscan` is a full workhorse, and any speedups/optimizations/bugfixes that can be implemented would be key

**Comment by chengzhuzhang** [comment]
Adding one vote for putting cdscan enhancement on the "PRIORITY" queue..
